quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('add_stock/', views.add_stock, name='add_stock'),
    path('delete/<stock_id>', views.delete, name='delete'),
    path('delete_stock/', views.delete_stock, name='delete_stock'),
]

stocks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
]

quotes/models.py
from django.db import models

class Stock(models.Model):
	ticker = models.CharField(max_length=10)

	def __str__(self):
		return self.ticker

quotes/forms.py
from django.forms import ModelForm
from .models import Stock

class StockForm(ModelForm):
	class Meta:
		model = Stock
		fields = ['ticker']

quotes/views.py
#Copyright (c) Kevin Ochieng all rights deserved
from django.shortcuts import render, redirect
from .models import Stock
from .forms import StockForm
from django.contrib import messages

def home(request):
	import requests
	import json

	if request.method == 'POST':
		ticker = request.POST['ticker']
		api_request = requests.get("https://cloud.iexapis.com/stable/stock/" + ticker + "/quote?token=pk_8e69579dfbab4b5ba539bfd4495ed048")
		
		errorFound = False
		error = ''
		try:
			api = json.loads(api_request.content)
		except Exception as err:
			errorFound = True
			api = str(err)
			error = str(err)
		context = {
			'api':api,
			'errorFound':errorFound,
			'errorMessage':error
		}		
		return render(request, 'quotes/home.html', context)
	else:
		context = {
			'api':None,
			'errorFound':False,
			'ticker':'Enter a Ticker symbol above...'
		}				
		return render(request, 'quotes/home.html', context)

def about(request):

	context = {}
	return render(request, 'quotes/about.html', context)

def add_stock(request):
	import requests
	import json
	if request.method == 'POST':
		form = StockForm(request.POST or None)

		if form.is_valid():
			form.save()
			messages.success(request, ("Stock has been added"))
			return redirect('quotes:add_stock')
	else:
		stocks = Stock.objects.all()
		apis = []

		for ticker_item in stocks:
			api_request = requests.get("https://cloud.iexapis.com/stable/stock/" + str(ticker_item) + "/quote?token=pk_8e69579dfbab4b5ba539bfd4495ed048")
			
			errorFound = False
			error = ''
			try:
				api = json.loads(api_request.content)
				apis.append(api)
			except Exception as err:
				errorFound = True
				api = str(err)
				error = str(err)
				break

		context = {
			'apis':apis,
			'errorFound':errorFound,
			'errorMessage':error,
			'stocks': stocks
		}	

		return render(request, 'quotes/add_stock.html', context)

def delete(request, stock_id):
	item = Stock.objects.get(pk=stock_id)
	item.delete()
	messages.success(request, ("Stock has been deleted"))
	return redirect('quotes:delete_stock')

def delete_stock(request):
	stocks = Stock.objects.all()
	context = {'stocks' : stocks}
	return render(request, 'quotes/delete_stock.html', context)
	

quotes/templates/quotes/about.html
{% extends 'quotes/base.html' %}
{% block content %}

<h1>About Us</h1>

{% endblock %}

quotes/templates/quotes/add_stock.html
{% extends 'quotes/base.html' %}
{% block content %}

<h1>Add Stock</h1>
<br>
<br>
<form class="form-inline my-2 my-lg-0" action="{% url 'quotes:add_stock' %}" method="POST">
	{% csrf_token %}
  	<input class="form-control mr-sm-2" type="search" placeholder="Add to Portfolio" aria-label="Search" name="ticker">
  	<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Add Stock</button>
</form>
<br>
<br>
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Company Name</th>
      <th scope="col">Ticker</th>
      <th scope="col">Stock Price</th>
      <th scope="col">Previous Close</th>
      <th scope="col">Market Cap</th>
      <th scope="col">YTD Change</th>
      <th scope="col">52 Wk High</th>
      <th scope="col">52 Wk Low</th>
    </tr>
  </thead>
  <tbody>  		
	{% for list_item in apis%}
		<tr>
			<th scope="row">{{list_item.companyName}}</th>
		    <td>{{list_item.symbol}}</td>
			<td>${{list_item.latestPrice}}</td>
			<td>${{list_item.previousClose}}</td>
			<td>${{list_item.marketCap}}</td>
			<td>{{list_item.ytdChange}}%</td>
			<td>${{list_item.week52High}}</td>
			<td>${{list_item.week52Low}}</td>
		</tr>
	{% endfor %}  		
  </tbody>
</table>

<br><br>

{% endblock %}

quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Stock Portofolio</title>
  </head>
  <body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <a class="navbar-brand" href="{% url 'quotes:home' %}">Stock Portfolio</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'quotes:about' %}">About</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'quotes:add_stock' %}">Add Stock</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'quotes:delete_stock' %}">Delete Stock</a>
	      </li>	      
	    </ul>
	    <form class="form-inline my-2 my-lg-0" action="{% url 'quotes:home' %}" method="POST">
	    	{% csrf_token %}
	      <input class="form-control mr-sm-2" type="search" placeholder="Get Stock Quote" aria-label="Search" name="ticker">
	      <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Stock Quote</button>
	    </form>
	  </div>
	</nav>  	
  	<div class="container">
  		<br>
  		{% if messages %}
  			{% for message in messages %}
  				<div class = "alert alert-warning alert-dismissable" role="alert">
  					<button class="close" data-dismiss="alert">
  						<small><sup>x</sup></small>
  					</button>
  					{{ message }}
  				</div>
  				<br>
  			{% endfor %}
  		{% endif %}

		{% block content %}

		{% endblock %}  		
  	</div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

quotes/templates/quotes/delete_stock.html
{% extends 'quotes/base.html' %}
{% block content %}

	<h1>Delete Stock</h1>
	<br><br>
	{% if stocks %}
		{% for stock in stocks %}
			{{stock}} - <a href="{% url 'quotes:delete' stock.id %}" class="btn btn-secondary">Delete Stock</a><br><br>
		{% endfor %}
		
	{% else %}
		You dont have any Stocks...
	{% endif %}

{% endblock %}

quotes/templates/quotes/home.html
{% extends 'quotes/base.html' %}
{% block content %}

{% if ticker %}
	{{ticker}}
{% endif %}

{% if api %}
	{%  if errorFound %}
		{{ errorMessage }}<br>
		There was a problem with your ticker symbol,
		please try again
	{% else %}
		<h1>{{api.companyName}}</h1>
		Price $: {{api.latestPrice}}<br/>
		Previous Close: {{api.previousClose}}<br/>
		Market Cap: {{api.marketCap}}<br/>
		YTD Change: {{api.ytdChange}}<br/>
		52 Wk High: {{api.week52High}}<br/>
		52 Wk Low: {{api.week52Low}}<br/>
	{% endif %}
{% endif %}

{% endblock %}